apiVersion: v1
kind: Service
metadata:
  name: frontendWeb-service
spec:
  selector: 
    app: frontendWeb
  ports:
  - name: http
    port: 5051 
    targetPort: 5051

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendWeb-deployment
spec:
  minReadySeconds: 1
  selector:
    matchLabels:
      app: frontendWeb
  replicas: 1

  template:
    metadata:
      labels:
        app: frontendWeb
    spec:
      containers:
      - name: JoBAR_FrontendWeb
        image: node:latest
        ports:
        - name: http
          containerPort: 5051
        tty: true
        volumeMounts:
        - name: frontendWeb-volume
          mountPath: /app
      volumes:
      - name: frontendWeb-volume
        persistentVolumeClaim:
          claimName: frontendWeb-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontendWeb-pvc
  labels:
    app: frontendWeb
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv-for: frontendWeb

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: frontendWeb-pv
  labels:
    app: frontendWeb
    pv-for: frontendWeb
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /run/desktop/mnt/host/c/[path]/frontendweb_data