apiVersion: v1
kind: PersistentVolume
metadata:
  name: frontendweb-pv
  labels:
    app: frontendweb
    pv-for: frontendweb
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /run/desktop/mnt/host/c/Users/dingf/Desktop/JoBar_k8s/resource/frontendweb_data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontendweb-pvc
  labels:
    app: frontendweb
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      pv-for: frontendweb
---
apiVersion: v1
kind: Service
metadata:
  name: frontendweb-service
spec:
  selector: 
    app: frontendweb
  ports:
  - name: http
    port: 5051 
    targetPort: 5051

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendweb-deployment
spec:
  minReadySeconds: 1
  selector:
    matchLabels:
      app: frontendweb
  replicas: 1

  template:
    metadata:
      labels:
        app: frontendweb
    spec:
      containers:
      - name: frontendweb
        image: node:latest
        ports:
        - name: http
          containerPort: 5051
        tty: true
        volumeMounts:
        - name: frontendweb-volume
          mountPath: /app
      volumes:
      - name: frontendweb-volume
        persistentVolumeClaim:
          claimName: frontendweb-pvc

