#when deploy the nginx server, you should declare the configmap by shell mode command
#reference: https://ithelp.ithome.com.tw/articles/10196153

apiVersion: v1
kind: PersistentVolume
metadata:
  name: letsencrypt-pv
  labels:
    app: nginx
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ./letsencrypt
  persistentVolumeReclaimPolicy: Retain ###i'm not sure the function of this line

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
  labels:
    app: nginx
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ./nginx_data
  persistentVolumeReclaimPolicy: Retain ###i'm not sure the function of this line

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: letsencrypt-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv-selector: letsencrypt-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv-selector: data-pv

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: JoBAR_NGINX
          image: jc21/nginx-proxy-manager:latest
          ports:
            - name: http1
              containerPort: 80
            - name: http2
              containerPort: 81
            - name: https
              containerPort: 443
          volumeMounts:
            - name: data-volume
              mountPath: /data
            - name: letsencrypt-volume
              mountPath: /etc/letsencrypt
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
        - name: letsencrypt-volume
          persistentVolumeClaim:
            claimName: letsencrypt-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    name: nginx-deployment
  type: LoadBalancer
  ports:
    - name: http1
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: http2
      protocol: TCP
      port: 81
      targetPort: 81
