#https://github.com/tobru/odoo-pos-distribution
#https://github.com/akhdaniel/odoo-kubernetes

apiVersion: v1
kind: Service
metadata:
  name: odoo-service
spec:
  selector: 
    app: odoo
  ports:
  - name: http
    port: 8069  
    targetPort: 8069

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-deployment
spec:
  minReadySeconds: 1
  selector:
    matchLabels:
      app: odoo
  replicas: 1

  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: JoBAR_Odoo
        image: odoo:16
        ports:
        - name: http
          containerPort: 8069
        env:
        - name: POSTGRES_USER   #POSTGRES_USER: postgresuser
          valueFrom:
            secretKeyRef:
              name: secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD   #POSTGRES_PASSWORD: postgrespasswd
          valueFrom:
            secretKeyRef:
              name: secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB   #POSTGRES_DB: postgres
          valueFrom:
            secretKeyRef:
              name: secret
              key: POSTGRES_DB
        - name: PGHOST   #PGHOST: DB
          valueFrom:
            secretKeyRef:
              name: secret
              key: PGHOST
        - name: PGPORT   #PGPORT: "5432"
          value: "5432"
        - name: ODOO_HTTP_SOCKET_TIMEOUT
          value: 20
        volumeMounts:
        - name: odoo-config-volume
          mountPath: /etc/odoo/
        - name: odoo-addons-volume
          mountPath: /mnt/extra-addons
        - name: odoo-webdata-volume
          mountPath: /var/lib/odoo
        - name: odoo-log-volume
          mountPath: /var/log
      volumes:
      - name: odoo-config-volume
        persistentVolumeClaim:
          claimName: odoo-config-pvc
      - name: odoo-addons-volume
        persistentVolumeClaim:
          claimName: odoo-addons-pvc
      - name: odoo-webdata-volume
        persistentVolumeClaim:
          claimName: odoo-webdata-pvc
      - name: odoo-log-volume
        persistentVolumeClaim:
          claimName: odoo-log-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-config-pvc
  labels:
    app: odoo
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv-for: odoo-config

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-config-pv
  labels:
    app: odoo
    pv-for: odoo-config
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /run/desktop/mnt/host/c/[path]/odoo_config

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-addons-pvc
  labels:
    app: odoo
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv-for: odoo-addons

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-addons-pv
  labels:
    app: odoo
    pv-for: odoo-addons
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /run/desktop/mnt/host/c/[path]/odoo_addons

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo_webdata-pvc
  labels:
    app: odoo
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv-for: odoo_webdata

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo_webdata-pv
  labels:
    app: odoo
    pv-for: odoo_webdata
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /run/desktop/mnt/host/c/[path]/odoo_webdata

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-log-pvc
  labels:
    app: odoo
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv-for: odoo-log

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-log-pv
  labels:
    app: odoo
    pv-for: odoo-log
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /run/desktop/mnt/host/c/[path]/log/odoo_log




      
    