apiVersion: v1
kind: Service
metadata:
  name: odoo-bot-service
spec:
  selector: 
    app: odoo-bot
  ports:
  - name: http
    port: 5000  
    targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-bot
spec:
  minReadySeconds: 1
  selector:
    matchLabels:
      app: odoo-bot
  replicas: 1

  template:
    metadata:
      labels:
        app: odoo-bot
    spec:
      containers:
      - name: odoo-bot
        image: ubuntu:latest
        ports:
        - name: http
          containerPort: 5000
        stdin: true
        tty: true
        command:
          - ["bash"]
        volumeMounts:
        - name: odoo-bot-pvc
          mountPath: /Bot
      volumes:
      - name: odoo-bot-pvc
        persistentVolumeClaim:
          claimName: odoo-bot-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-bot-pvc
  labels:
    app: odoo-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-bot-pv
  labels:
    app: odoo-bot
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: ./bot_data