apiVersion: v1
kind: Service
metadata:
  name: odoo-bot-service
spec:
  selector: 
    app: odoo-bot
  ports:
  - name: http
    port: 5000  
    targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-bot-deployment
spec:
  minReadySeconds: 1
  selector:
    matchLabels:
      app: odoo-bot
  replicas: 1

  template:
    metadata:
      labels:
        app: odoo-bot
    spec:
      containers:
      - name: JoBAR_LineBot
        image: linebot
        ports:
        - name: http
          containerPort: 5000
        tty: true
        volumeMounts:
        - name: odoo-bot-volume
          mountPath: /app
      volumes:
      - name: odoo-bot-volume
        persistentVolumeClaim:
          claimName: odoo-bot-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-bot-pvc
  labels:
    app: odoo-bot
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv-for: odoo-bot

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-bot-pv
  labels:
    app: odoo-bot
    pv-for: odoo-bot
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /run/desktop/mnt/host/c/[path]/bot_data