apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  type: NodePort
  selector: 
    app: pgadmin
  ports:
  - name: http
    port: 5050
    targetPort: 80
    nodePort: 30082

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
spec:
  minReadySeconds: 1
  selector:
    matchLabels:
      app: pgadmin
  replicas: 1

  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: andrewchang0910@gmail.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: andrewchang!QAZ@WSX
        ports:
        - name: http
          containerPort: 80
