#https://godleon.github.io/blog/Kubernetes/k8s-StatefulSets-Overview/
#https://medium.com/@suyashmohan/setting-up-postgresql-database-on-kubernetes-24a2a192e962
#https://loft.sh/blog/kubernetes-statefulset-examples-and-best-practices/
apiVersion: v1
kind: Service
metadata:
  name: postgres-service # Sets service name
  labels:
    app: postgres # Labels and Selectors
spec:
  selector:
    app: postgres
  ports:
    - name: http
      port: 5432  
      targetPort: 5432

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv  # Sets PV's name
  labels:
    type: local  # Sets PV's type to local
    app: postgres
    pv-for: postgres
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi # Sets PV Volume
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c//Users/intel/Desktop/JoBar_k8s/resource/pgdata
    

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres
        env:
        - name: POSTGRES_USER   #POSTGRES_USER: postgresuser
          valueFrom:
            secretKeyRef:
              name: secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD   #POSTGRES_PASSWORD: postgrespasswd
          valueFrom:
            secretKeyRef:
              name: secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB   #POSTGRES_DB: postgres
          valueFrom:
            secretKeyRef:
              name: secret
              key: POSTGRES_DB
        ports:
        - containerPort: 5432  #不用name?
        volumeMounts:
        - name: postgres-pvc
          mountPath: /var/lib/postgresql/data
  # 使用 persistent volume 來確保資料不會因為 pod reschedule 而消失
  # 以下是使用 volumeClaimTemplates + StorageClass 來完成
  volumeClaimTemplates:
  - metadata:
      name: postgres-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi

