#https://godleon.github.io/blog/Kubernetes/k8s-StatefulSets-Overview/
#https://medium.com/@suyashmohan/setting-up-postgresql-database-on-kubernetes-24a2a192e962
#https://loft.sh/blog/kubernetes-statefulset-examples-and-best-practices/
apiVersion: v1
kind: Service
metadata:
  name: redis-service # Sets service name
  labels:
    app: redis # Labels and Selectors
spec:
  selector:
    app: redis
  ports:
    - name: http
      port: 6379  
      targetPort: 6379

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv  # Sets PV's name
  labels:
    app: redis
    pv-for: redis-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi # Sets PV Volume
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c/Users/intel/Desktop/JoBar_k8s/resource/redeis
    

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-statefulset
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: "redis"
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: JoBAR_redis
        image: redis:latest
        ports:
        - containerPort: 6379 
        volumeMounts:
        - name: redis-pvc
          mountPath: /var/lib/postgresql/data
  # 使用 persistent volume 來確保資料不會因為 pod reschedule 而消失
  # 以下是使用 volumeClaimTemplates + StorageClass 來完成
  volumeClaimTemplates:
  - metadata:
      name: redis-pvc
      labels:
        type: local  # Sets PV's type to local
        app: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
      selector:
        matchLabels:
          pv-for: redis-pv


