apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  #[password]: cGFzc3dvcmQxMjM=  //Base64 encoded value of "password123"
  POSTGRES_USER: #Base64() run"echo -n 'xxxx' | base64"   #----odoo
  POSTGRES_PASSWORD: #Base64() run"echo -n 'xxxx' | base64" #----odoo
  POSTGRES_DB: #Base64() run"echo -n 'xxxx' | base64" #----odoo
  PGHOST: #Base64() run"echo -n 'xxxx' | base64"  #----odoo

  

