apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  #[password]: cGFzc3dvcmQxMjM=  //Base64 encoded value of "password123"
  POSTGRES_USER: cm9vdA==  #Base64(root)
  POSTGRES_PASSWORD: cm9vdHBhc3M=  #Base64(rootpass) 
  POSTGRES_DB: cG9zdGdyZXM= #Base64(postgres)
  PGHOST: cG9zdGdyZXMtc2VydmljZQ==  #Base64(postgres-service)  //使用k8s cluster內部的DNS連到所對應的service

  

